// 1. Enums: Standardize status values to prevent "magic strings"
export enum BookingStatus {
  PENDING = "pending",
  CONFIRMED = "confirmed",
  CANCELLED = "cancelled",
  COMPLETED = "completed",
}

export enum DataStatus {
  PUBLISHED = "published",
  DRAFT = "draft",
  ARCHIVED = "archived",
}

export enum PaymentStatus {
  UNPAID = "unpaid",
  DEPOSIT_PAID = "deposit_paid",
  PAID = "paid",
  REFUNDED = "refunded",
}

export enum PaymentMethod {
  CASH = "cash",
  VNPAY = "vnpay",
  MOMO = "momo",
  BANK_TRANSFER = "bank_transfer",
  CREDIT_CARD = "credit_card",
}

// 2. Base Entity: Fields automatically generated by Directus
export interface BaseEntity {
  date_created: string; // ISO 8601 String
  date_updated?: string;
  sort?: number;
}

// 3. File Interface (Directus Assets)
export interface DirectusFile {
  id: string;
  filename_disk: string;
  width?: number;
  height?: number;
  title?: string;
  url?: string; // Computed field
}

// 3b. M2M File Interface (Junction Table)
export interface M2MFile {
  directus_files_id: DirectusFile | string;
}

// 4. Domain Interfaces (Mapped 1:1 with Schema v8.0)

export interface Branch extends BaseEntity {
  id: number;
  status: DataStatus;
  name: string;
  slug: string;
  address: string;
  phone: string;
  map_url?: string;
  images?: M2MFile[] | string[]; // Updated for M2M
  description?: string; // HTML format
}

export interface RoomType extends BaseEntity {
  id: number;
  status: DataStatus;
  name: string;
  slug: string;
  price_base: number;
  inventory_count: number; // Core logic for availability
  capacity_adults: number;
  capacity_children: number;
  size_sqm?: number; // Room size in square meters
  bed_type?: "king" | "queen" | "twin" | "king_sofa"; // Bed type
  view_type?: "sea_view" | "river_view" | "city_view" | "garden_view" | "no_window"; // View type
  amenities?: string[]; // Array of amenity codes: ['wifi', 'tv', 'ac', ...]
  description?: string; // HTML format
  images?: M2MFile[] | string[]; // Updated for M2M
  branch_id: number | Branch;
}

export interface Booking extends BaseEntity {
  id: number;
  status: BookingStatus;
  code?: string; // Unique booking code: AMY-YYYYMMDD-XXXX
  customer_name: string;
  customer_phone: string;
  customer_email?: string;
  check_in: string; // YYYY-MM-DD
  check_out: string; // YYYY-MM-DD
  total_price: number;
  payment_status?: PaymentStatus;
  payment_method?: PaymentMethod;
  payment_transaction_id?: string; // Transaction ID from payment gateway
  note?: string;
  guests: number;
  items?: BookingItem[];
}

export interface BookingItem extends BaseEntity {
  id: number;
  status: DataStatus;
  booking_id: number | Booking;
  room_type_id: number | RoomType;
  quantity: number;
  price_snapshot: number; // Snapshot price at time of booking
}
